  default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost

development:
  <<: *default
  database: hello_development

test:
  <<: *default
  database: hello_test
production:
  <<: *default
  database: hello_production